<a href="https://colab.research.google.com/github/deviramasamy/Python/blob/main/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy array Vs Python List**

Why Numpy array:-Numerical Python. Numpy array is widely used object in Numpy Library,which is similar to list. Array is homegeoneous wheareas list is heterogeneous. Every array is a list but not every list is a array.

It is used for scientific calculation and it is a library. Basic for other major libraries like pandas.

1.   Fast-optimized-Less bytes of memory
2.   No type checking when iterating through object.
2.   less memory and speed
3.   convinient-lot of functionalities

uses continuous memory.

List: can do insertion, deletion,appending, concatenation etc
Numpy-Lot more than list

**Applications in NumPy** 

Matlab replacement
plotting
backend
machine learning



Numpy-uses fixed type. eg: a number in a matirx

5 requires lot more space in list vecause list stores value as size,reference count,object type and object value whereas NumPy stores only in a memory space of 4 bytes



Import numpy as np

In [23]:
#printing a numpy array
import numpy as np
a=np.array([1,2,3],dtype='int16')
print(a)
#2d array
z = np.array([[9,8,7],[11,5,6]])
print(z)


[1 2 3]
[[ 9  8  7]
 [11  5  6]]


In [26]:
#get dimension - ndim
print(a.ndim)
print(z.ndim)
#get shape
print(a.shape)
#get type
print(a.dtype)
#get itemsize-16 is 2 bytes, 32 is 8 bytes
print(a.itemsize)
#get totalsize
print(a.nbytes)

1
2
(3,)
int16
2
6


In [27]:
#to find out why numpy array
import time
import sys
b=range(1000)
print(sys.getsizeof(5),len(b))
print(sys.getsizeof(5)*len(b))

#numpy
c=np.arange(1000)
print(c.size*c.itemsize)

#speed
size =100000
L1=range(size)
L2=range(size)
a1=np.arange(size)
a2=np.arange(size)


28 1000
28000
8000


In [51]:
#accessing/changing specific elements, rows, columns etc.
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print(c.shape)
#get a specific element [r,c]
print(c[1,5])  
print(c[0,4])
#get a specific row
print(c[0,:])
#get a specific column
print(c[:,2])
#get a little more fancy [startindex,endindex,stepsize]
print(c[1,1:6:3])
#to change a value in the list
c[1,5] =20
print(c)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
13
5
[1 2 3 4 5 6 7]
[ 3 10]
[ 9 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [55]:
#3d example
d=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(d)
#specific element-work outside in
print(d[0,1,1])


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4


In [58]:
#Initialising different types of array
#all 0's matrix
np.zeros((2,3,3,2))
#all 1's matrix
np.ones(())

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])