<a href="https://colab.research.google.com/github/deviramasamy/Python/blob/main/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy array Vs Python List**

Why Numpy array:-Numerical Python. Numpy array is widely used object in Numpy Library,which is similar to list. Array is homegeoneous wheareas list is heterogeneous. Every array is a list but not every list is a array.

It is used for scientific calculation and it is a library. Basic for other major libraries like pandas.

1.   Fast-optimized-Less bytes of memory
2.   No type checking when iterating through object.
2.   less memory and speed
3.   convinient-lot of functionalities

uses continuous memory.

List: can do insertion, deletion,appending, concatenation etc
Numpy-Lot more than list

**Applications in NumPy** 

Matlab replacement
plotting
backend
machine learning



Numpy-uses fixed type. eg: a number in a matirx

5 requires lot more space in list vecause list stores value as size,reference count,object type and object value whereas NumPy stores only in a memory space of 4 bytes



Import numpy as np

In [2]:
#printing a numpy array
import numpy as np
a=np.array([1,2,3],dtype='int16')
print(a)
#2d array
z = np.array([[9,8,7],[11,5,6]])
print(z)


[1 2 3]
[[ 9  8  7]
 [11  5  6]]


In [ ]:
#get dimension - ndim
print(a.ndim)
print(z.ndim)
#get shape
print(a.shape)
#get type
print(a.dtype)
#get itemsize-16 is 2 bytes, 32 is 8 bytes
print(a.itemsize)
#get totalsize
print(a.nbytes)

1
2
(3,)
int16
2
6


In [ ]:
#to find out why numpy array
import time
import sys
b=range(1000)
print(sys.getsizeof(5),len(b))
print(sys.getsizeof(5)*len(b))

#numpy
c=np.arange(1000)
print(c.size*c.itemsize)

#speed
size =100000
L1=range(size)
L2=range(size)
a1=np.arange(size)
a2=np.arange(size)


28 1000
28000
8000


In [ ]:
#accessing/changing specific elements, rows, columns etc.
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print(c.shape)
#get a specific element [r,c]
print(c[1,5])  
print(c[0,4])
#get a specific row
print(c[0,:])
#get a specific column
print(c[:,2])
#get a little more fancy [startindex,endindex,stepsize]
print(c[1,1:6:3])
#to change a value in the list
c[1,5] =20
print(c)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
13
5
[1 2 3 4 5 6 7]
[ 3 10]
[ 9 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
#3d example
d=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(d)
#specific element-work outside in
print(d[0,1,1])


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4


In [ ]:
#Initialising different types of array
#all 0's matrix
np.zeros((2,3,3,2))
#all 1's matrix
np.ones(())
#any other number (full_like)
np.full_like(a,4)
#random decimal
np.random.rand(4,2,3)
#random integer
np.random.randint(4,7,size =(3,3))


array([[5, 4, 4],
       [5, 6, 4],
       [6, 4, 4]])

In [ ]:
#creating a matrix
output = np.ones((5,5))
print(output)

e=np.zeros((4,4))
e[1,1]=9
print(e)

output[1:5,1:5]=e
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 9. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 9. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [ ]:
#copying function along with NumPy
f=np.array([1,2,3])
g=f
print(f)
print(g)
#below example will make both the list change which is not we want.
g[0]=10
print(g)
print(f)
#If we want to make a copy of a list and do the changes
h=np.array([1,2,3])
i=h.copy()
print(i)

i[1]=5
print(i)
print(h)

[1 2 3]
[1 2 3]
[10  2  3]
[10  2  3]
[1 2 3]
[1 5 3]
[1 2 3]


In [ ]:
#Mathematics capablity of Numpy
j=np.array([1,2,3,4,5])
k=np.array([1,3,3,4,5])
print(j)

print(j+2)
print(j-2)
print(j*2)
print(j/2)
print(j+k)

#take the sin
print(np.sin(j))
print(np.cos(j))
print(np.sin(k))

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 2  5  6  8 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 0.84147098  0.14112001  0.14112001 -0.7568025  -0.95892427]


In [ ]:
#Linear Algebra
alg1=np.ones((2,3))
print(alg1)

alg2=np.full((3,2),4)
print(alg2)

#print(alg1*alg2)#this wont work as the matrix has got a function for multiplication
alg3 = np.matmul(alg1,alg2)
print(alg3)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]
[[12. 12.]
 [12. 12.]]


In [ ]:
#statistics
stats1=np.array([[1,2,3],[4,5,6]])
stats2=np.min(stats1)
print(stats2)

stats1=np.array([[1,2,3],[4,5,6]])
stats2=np.max(stats1,axis=0)
print(stats2)



1
[4 5 6]


In [ ]:
#Reorganising array
reorg = np.array([[1,2,3,4],[5,6,7,8]])
print(reorg)
print(reorg.shape)
reorg1=reorg.reshape((4,2))
print(reorg1)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
#vertically stacking vectors
ver1=np.array([1,2,3,4,5])
ver2=np.array([6,7,8,9,0])
ver3=np.vstack([ver1,ver2,ver2,ver1])
print(ver3)

#Horizontal stacking
np.hstack

[[1 2 3 4 5]
 [6 7 8 9 0]
 [6 7 8 9 0]
 [1 2 3 4 5]]


<function numpy.hstack(tup)>

In [44]:
#Miscellaneous
#local data from file
np.genfromtxt('/content/Bigmarket.csv',delimiter=',')

array([[   nan,    nan,    nan],
       [   nan,    nan, 31037.],
       [   nan,    nan, 20722.],
       [   nan,    nan, 24557.],
       [   nan,    nan, 34649.],
       [   nan,    nan, 29795.],
       [   nan,    nan, 29133.],
       [   nan,    nan, 22695.],
       [   nan,    nan, 28312.],
       [   nan,    nan, 31454.],
       [   nan,    nan, 46267.],
       [   nan,    nan, 32961.],
       [   nan,    nan, 26451.],
       [   nan,    nan, 47814.],
       [   nan,    nan, 36069.],
       [   nan,    nan, 31874.],
       [   nan,    nan, 27253.],
       [   nan,    nan, 40241.],
       [   nan,    nan, 47488.],
       [   nan,    nan, 25432.],
       [   nan,    nan, 33880.],
       [   nan,    nan, 29487.],
       [   nan,    nan, 40001.],
       [   nan,    nan, 46482.],
       [   nan,    nan, 46313.],
       [   nan,    nan, 47594.]])

In [42]:
#you can index with a list in numpy
index=np.array([1,2,3,4,5,6,7,8])
print(index[[2,3,4]])




[3 4 5]


In [45]:
#Joining arrays
a=np.array([[1,2],[3,4]])
print('first array',a)
b=np.array([[5,6],[7,8]])
print('second array',b)
print('joining the arrays along axis 1')
print(np.concatenate((a,b),axis=1))
print('joining the arrays along axis 0')
print(np.concatenate((a,b),axis=0))

#String Functions
#concatenation with strings
print(np.char.add(["hello","hi"],["abc","def"]))
print(np.char.multiply("hello",3))


first array [[1 2]
 [3 4]]
second array [[5 6]
 [7 8]]
joining the arrays along axis 1
[[1 2 5 6]
 [3 4 7 8]]
joining the arrays along axis 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
['helloabc' 'hidef']
hellohellohello


In [47]:
#Other fill function
#fill function
print(np.char.center("hello",20,fillchar='-'))
#Capitalise-Capitalises the first character
print(np.char.capitalize("hello world"))
#title-capitalises all the first character of the words
print(np.char.title("How r u doing"))
#lowercase
print(np.char.lower("Hello world"))
print(np.char.lower(["Hello", "World"]))
#uppercase
print(np.char.upper("Hello world"))
print(np.char.upper(["Hello", "World"]))
#split function
print(np.char.split("Hello world"))
print(np.char.splitlines("Hello\n world"))
#strip function-strips the last letter in all the items in the array.
print(np.char.strip(["Helloh", "worldh"],'h'))
#replace function
print(np.char.replace('He is a good man','is','was'))
print(np.char.replace('He is a good man','good','bad'))
#join
print(np.char.join([':','-'],['dmy','dmy']))

-------hello--------
Hello world
How R U Doing
hello world
['hello' 'world']
HELLO WORLD
['HELLO' 'WORLD']
['Hello', 'world']
['Hello', ' world']
['Hello' 'world']
He was a good man
He is a bad man
['d:m:y' 'd-m-y']


In [68]:
#Array Manipulation
#changing shape
a= np.arange(9)
print('The original array', a)

b=a.reshape(3,3)
print('The modified array', b)
#flatten array 
print(b.flatten())
#Fortran
print(b.flatten(order='F'))
print(b.flatten(order='C'))
print(b.flatten(order='A'))
#reshape
a=np.arange(12)
b=a.reshape(3,4)
print(b)
#transpose
print(np.transpose(a))

The original array [0 1 2 3 4 5 6 7 8]
The modified array [[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 3 6 1 4 7 2 5 8]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [76]:
#Numpy Arithmetic Operations
a=np.arange(9).reshape(3,3)
print(a)
b=np.array([10,100,10])
print(b)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 10 100  10]
[[ 10 101  12]
 [ 13 104  15]
 [ 16 107  18]]
[[-10 -99  -8]
 [ -7 -96  -5]
 [ -4 -93  -2]]
[[  0 100  20]
 [ 30 400  50]
 [ 60 700  80]]
[[0.   0.01 0.2 ]
 [0.3  0.04 0.5 ]
 [0.6  0.07 0.8 ]]


In [84]:
#Slicing array
a=np.arange(20)
print(a)
print(a[4:])
print(a[:5])
print(a[::-1])
print(a[:])
#start,stop, step
s=slice(2,18,2)
print(a[s])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16]


In [ ]:
#Iterating over array
